httpProxy: "http://127.0.0.1:8066"

httpsProxy: "https://127.0.0.1:8066"

npmRegistryServer: "https://registry.npm.taobao.org"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
